# Permalinks
permalink:        /:title

# Setup
title:            Oblika
tagline:          Design Data Interfaces
description:      Making awesome software
baseurl:  ''
languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true

# Pagination number
#paginate:         10

# category page
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
claim:
    en: "Communicaton by algorithms"
    es: "Comunicación con algoritmos"
#menu translation
t:
  en:
    home:
      name: "Home"
      url: "/"
    projects:
      name: "Projects"
      url: "#projects"
    services:
      name: "Services"
      url: "#services"
    team:
      name: "Team"
      url: "#team"
    contact:
      name: "Contact"
      url: "#contact"
  es:
      home:
        name: "Home"
        url: "/"
      projects:
        name: "Proyectos"
        url: "#projects"
      services:
        name: "Servicios"
        url: "#services"
      team:
        name: "Equipo"
        url: "#team"
      contact:
        name: "Contacto"
        url: "#contact"
